### ISSUE TITLE
Issue with a create-a-virtual-card

### ISSUE THREAD

**Issue by kitsela** [svb/svb-api#1]
Hello. 
I am trying to use svb-api. 
I use API methods from the following documentation:
http://docs.svbplatform.com/virtualcards/#create-a-virtual-card
When I try to add new virtual card using the endpoint "POST /v1/virtualcards" I get an error
{
    "error": "Company template not found."
} 
Also, the documentation doesn't contain this type of error. Should I add some extra parameter to the request? Could you please provide a valid request example?

**Comment by jimbru** [comment]
@kitsela If you email apisupport@svb.com someone will be able to help you debug. Thanks.
